baseURL = 'https://b-gg.com'
languageCode = 'en-us'
title = 'Beyond Geek Guide'
theme = 'simple'

[params]
  description = 'Clear tech tutorials, software guides, and practical tips for everyone'
  author = 'B-GG Team'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "Tutorials"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    name = "Java"
    url = "/topics/java/"
    parent = "Programming"
    weight = 31
  
  [[menu.main]]
    name = "Go"
    url = "/topics/golang/"
    parent = "Programming"
    weight = 32
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
