baseURL = 'https://b-gg.com'
languageCode = 'en-us'
title = 'Beyond Geek Guide'
theme = 'simple'

[params]
  description = 'Clear tech tutorials, software guides, and practical tips for everyone'
  author = 'B-GG Team'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
name = "Topics"
url = "/topics/"
weight = 20
  [[menu.main]]
    name = "Topics"
    url = "/topics/"
    weight = 25
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
